<?php
// This file generated by Propel 1.6.6-dev convert-conf target
// from XML runtime conf file /home/jleger/projects/php/activitystreams-example/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'activitystreams_blog_example' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=activitystreams_blog_example',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'activitystreams_blog_example',
  ),
  'generator_version' => '1.6.6-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-Blog-conf.php');
return $conf;